### ISSUE TITLE
Install fails with key not found

### ISSUE THREAD

**Issue by smonani** [innodatalabs/ilabs.s3util#1]
We tried this approach. But during the install, this fails for our case as it tries to query S3 using a sub folder prefix, which in itself is not a key. Here's a sample pip output.

F:\Source>pip install sm_core==0.0.1 --extra-index-url https://s3-eu-west-1.amazonaws.com/sm-python-packages -v
Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
Config variable 'Py_UNICODE_SIZE' is unset, Python ABI tag may be incorrect
Collecting sm_core==0.0.1
  2 location(s) to search for versions of sm-core:
  * https://pypi.python.org/simple/sm-core/
  * https://s3-eu-west-1.amazonaws.com/sm-python-packages/sm-core/
  Getting page https://pypi.python.org/simple/sm-core/
  Looking up "https://pypi.python.org/simple/sm-core/" in the cache
  No cache entry available
  Starting new HTTPS connection (1): pypi.python.org
  "GET /simple/sm-core/ HTTP/1.1" 404 28063
  Status code 404 not in [200, 203, 300, 301]
  Could not fetch URL https://pypi.python.org/simple/sm-core/: 404 Client Error: Not Found for url: https://pypi.python.org/simple/sm-core/ - skipping
  Getting page https://s3-eu-west-1.amazonaws.com/sm-python-packages/sm-core/
  Looking up "https://s3-eu-west-1.amazonaws.com/sm-python-packages/sm-core/" in the cache
  No cache entry available
  Starting new HTTPS connection (1): s3-eu-west-1.amazonaws.com
  "GET /sm-python-packages/sm-core/ HTTP/1.1" 404 None
  Status code 404 not in [200, 203, 300, 301]
  Could not fetch URL https://s3-eu-west-1.amazonaws.com/sm-python-packages/sm-core/: 404 Client Error: Not Found for url: https://s3-eu-west-1.amazonaws.com/sm-python-packages/sm-core/ - skipping
  Could not find a version that satisfies the requirement sm_core==0.0.1 (from versions: )
Cleaning up...
No matching distribution found for sm_core==0.0.1
Exception information:
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\python27\lib\site-packages\pip\commands\install.py", line 335, in run
    wb.build(autobuilding=True)
  File "c:\python27\lib\site-packages\pip\wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "c:\python27\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "c:\python27\lib\site-packages\pip\req\req_set.py", line 554, in _prepare_file
    require_hashes
  File "c:\python27\lib\site-packages\pip\req\req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "c:\python27\lib\site-packages\pip\index.py", line 514, in find_requirement
    'No matching distribution found for %s' % req
DistributionNotFound: No matching distribution found for sm_core==0.0.1

Any idea how to get around this?

Thanks,
Sid

**Comment by mkroutikov** [comment]
what is the content of your `pip.conf` ? we use this internally on a large scale, so it is most likely a configuration problem (or insufficient documentation).

Please, do not use `--extra-index-url` flag.

Post the content of your `pip.ini` (or `pip.conf`) and trace from pip (without --extra-index-url flag)

**Comment by mkroutikov** [comment]
Closing as you were apparently not following the instructions. 

Specifically, you MUST use cloudfront web on top of your S3 busket.

**Comment by smonani** [comment]
Found the real issue, it was custom policies on our end causing the issue.

**Comment by mkroutikov** [comment]
thank you for reporting the resolution!
